### ISSUE TITLE
Clarify relationship with pwc?

### ISSUE THREAD

**Issue by remram44** [paperswithcode/paperswithcode-data#1]
I knew about https://github.com/zziz/pwc, so I assumed https://paperswithcode.com/ was the website version of the same data. However it doesn't seem to be the case.

The subject is exactly the same, and so is the name. pwc has almost 9,000 stars so I assume you knew about it (if you didn't there's my answer!). Could you clarify the relationship? Inspiration, reboot, coincidence?

**Comment by rstojnic** [comment]
Hi @remram44. The original paperswithcode.com website was launched in June 2018:

https://www.reddit.com/r/MachineLearning/comments/8t0l40/p_papers_with_code_the_latest_machine_learning/

The first commit in the zziz/pwc repository was in September 2018:

https://github.com/zziz/pwc/commit/6805d5eb6de6c1e7c7932a3bfa916f4ea8dc123b

We don't know the creator of the pwc github repository, so my assumption is that it was inspired by the original paperswithcode website (I think he knew about us because he's been on our mailing list since June 2018).

**Comment by remram44** [comment]
I see! That is weird. If your website exists (with open-source collecting scripts) then I'm not sure why someone would replicate it (manually?)

Thanks for coming back to me so quick!
