### ISSUE TITLE
Invalid gzips linked from README

### ISSUE THREAD

**Issue by jmelot** [paperswithcode/paperswithcode-data#17]
Hi, thanks for this project and sharing your data! We pull updates regularly. Our pipeline had previously been running fine, but on September 30 we started getting `OSError: Not a gzipped file` from the python gzip library when trying to read any of the .json.gz files linked in the README of this repository. I just manually inspected the methods.json.gz linked in the README at https://production-media.paperswithcode.com/about/methods.json.gz , and when I run gunzip on it I get `gunzip: methods.json.gz: not in gzip format`. This file appears to be uncompressed. We can read the file as json, so not a big issue for us, but just letting you know.

**Comment by dhamaris** [comment]
Hi, we had a similar problem when trying to download from [https://paperswithcode.com/media/about/evaluation-tables.json.gz](https://paperswithcode.com/media/about/evaluation-tables.json.gz ) using java, we got this error:
`java.lang.Exception: java.util.zip.ZipException: Not in GZIP format`

In our case it doesn't happen all the time, we pull data every day since September and we got this error twice during November and today in the morning. If I run the same job by hand it works ok.

**Comment by jmelot** [comment]
@dhamaris fwiw I noticed in [this commit](https://github.com/paperswithcode/paperswithcode-data/commit/9e752b1f8f8deebbc88bb6a2f7f5554dd5afd96a) they updated the urls in the readme. Since I switched my code over to use the new urls, I haven't had further issues.

**Comment by dhamaris** [comment]
Thank you for the info @jmelot
